// src/vue/App.vue
<template>
  <div>
    <div class="vueFont">Hello vote vue</div>
    <wired-input ref="aInput" placeholder="Enter name"></wired-input>
    <wired-button @click="handleClick">Click Me</wired-button>
  </div>
</template>

<script>
import { WiredButton, WiredInput } from "wired-elements";
export default {
  methods: {
    handleClick() {
      alert(this.$refs.aInput.value);
    },
  },
};
</script>

<style scoped>
.vueFont {
  color: blue;
}
</style>

// src/react/App.jsx
import React from 'react';  // 这个必须要有
import { WiredButton, WiredInput } from "wired-elements"
import './x1.scss';

const App = () => {
    let textInput = React.createRef();

    const handleClick = () => {
        alert(textInput.current.value);
      }

    return <div className='container'>
        <span className='text'>Hello vite React</span>
        <wired-input placeholder="Enter name" ref={textInput}></wired-input>
        <wired-button onClick={handleClick}>Click Me</wired-button>
    </div>
}
export default App;
